### ISSUE TITLE
Unable to resolve service for type 'Passwordless.PasswordlessOptions' while attempting to activate 'Passwordless.PasswordlessClient'.' after upgrading to beta2

### ISSUE THREAD

**Issue by clarity99** [passwordless/passwordless-dotnet#56]
After upgrading to beta2 I get this error when trying to log in with passkey. 

```
Exception thrown: 'System.InvalidOperationException' in System.Private.CoreLib.dll: 'Unable to resolve service for type 'Passwordless.PasswordlessOptions' while attempting to activate 'Passwordless.PasswordlessClient'.'
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ThrowHelperUnableToResolveService(Type type, Type requiredBy)
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.AddTransientHelper[TClient,TImplementation](IServiceProvider s, IHttpClientBuilder builder)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|7_0>d.MoveNext()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__8.MoveNext()
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.<Invoke>d__11.MoveNext()
   at robRezCore.LogPostDataMiddleware.<InvokeAsync>d__3.MoveNext() in /Users/robertivanc/src/robrezervacije/robRezCore/Startup.cs:line 
```

My registration is as follows:

```
services.AddDefaultIdentity<User>(options =>
      {
        options.SignIn.RequireConfirmedAccount = true;
        options.User.RequireUniqueEmail = true;
        options.Password.RequireDigit = false;
        options.Password.RequireUppercase = false;
        options.Password.RequireNonAlphanumeric = false;
        options.Password.RequiredLength = 6;



      }).AddDefaultUI()
      .AddDefaultTokenProviders()
      .AddPasswordless(Configuration.GetSection("Passwordless"));
```

downgrading to beta1 makes it work again.

**Comment by Tyrrrz** [comment]
v2.0.0-beta3 should have this fixed. Please try it and let me know.

**Comment by clarity99** [comment]
That error is fixed, however now I get:

System.InvalidOperationException: The request message was already sent. Cannot send the same request message multiple times.
   at System.Net.Http.HttpClient.CheckRequestMessage(HttpRequestMessage request)
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at Passwordless.PasswordlessHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Passwordless/PasswordlessHttpHandler.cs:line 22
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Passwordless.PasswordlessClient.VerifyTokenAsync(String verifyToken, CancellationToken cancellationToken) in /_/src/Passwordless/PasswordlessClient.cs:line 83
   at Passwordless.AspNetCore.Services.Implementations.PasswordlessService`2.LoginUserAsync(PasswordlessLoginRequest loginRequest, CancellationToken cancellationToken) in /_/src/Passwordless.AspNetCore/Services/Implementations/PasswordlessService.cs:line 200
   at Passwordless.AspNetCore.PasswordlessApiEndpointRouteBuilderExtensions.<MapPasswordless>g__PasswordlessLogin|3_1[TRegisterBody](PasswordlessLoginRequest loginRequest, IPasswordlessService`1 passwordlessService, CancellationToken cancellationToken) in /_/src/Passwordless.AspNetCore/PasswordlessApiEndpointRouteBuilderExtensions.cs:line 69
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()

**Comment by Tyrrrz** [comment]
Interesting @clarity99, I will take a look tomorrow. Would you please create a new issue with this and repro code snippet?
